Add nether survival games
NucleoidMC/survival-games pull request #5
Opened 2021-02-23 20:27 UTC by yitzy299

Has nether wastes, crimson and warped forest biomes and soul sand valleys

- Piglins and gold ore for another interesting gameplay element
- New optional config value for generation of nether structures, defaults to 0
- New optional config value for dimension of map, defaults to overworld

2021-02-24 05:57 UTC, Gegy commented on src/main/java/supercoder79/survivalgames/game/map/SurvivalGamesChunkGenerator.java
> +    private final NoiseSampler2d treeDensityNoise;
Oh no

2021-02-24 07:50 UTC, yitzy299 commented on src/main/java/supercoder79/survivalgames/game/map/SurvivalGamesChunkGenerator.java
> +    private final NoiseSampler2d treeDensityNoise;
That is very concerning, bad GitHub

2021-02-24 14:47 UTC, SuperCoder7979 requested changes

2021-02-24 14:47 UTC, SuperCoder7979 commented on src/main/java/supercoder79/survivalgames/game/map/SurvivalGamesChunkGenerator.java
> +            outskirtGenerator.arrangePieces(start, new Identifier("survivalgames", "nether_outskirts"), 0);
This should go into the config, so you can specify what type of outskirts you want

2021-02-24 14:47 UTC, SuperCoder7979 commented on src/main/java/supercoder79/survivalgames/game/map/SurvivalGamesChunkGenerator.java
> +                    BlockState state = Blocks.STONE.getDefaultState();
might need to be put into the config for it to be netherrack

2021-02-24 14:47 UTC, SuperCoder7979 commented on src/main/java/supercoder79/survivalgames/game/map/SurvivalGamesChunkGenerator.java
> +                        state = Blocks.WATER.getDefaultState();
Putting this into the config would be good too

2021-02-24 14:47 UTC, SuperCoder7979 commented on src/main/resources/data/survivalgames/games/nether.json
> +  "nether_building_count": 10,
Should be generified into "outskirts_building_count" and "outskirts_pool" as stated above

2021-02-24 17:28 UTC, SuperCoder7979 requested changes

2021-02-24 17:28 UTC, SuperCoder7979 commented on src/main/java/supercoder79/survivalgames/game/map/SurvivalGamesChunkGenerator.java
> +            outskirtGenerator.arrangePieces(start, new Identifier("survivalgames", config.dimension.getPath() + "_outskirts_buildings"), 0);
Ideally we would have a custom codec entry for the outskirts path. That'll allow us to eventually add tropical buildings to tropical maps for example

2021-02-25 15:17 UTC, SuperCoder7979 approved these changes
Still needs a few fixes, but will do those myself. Thanks for this!

2021-02-25 15:18 UTC, merged

2021-02-25 16:09 UTC, yitzy299 commented
Thanks!